export const GET_PICTURES_BY_INDEX = "GET_PICTURES_BY_INDEX";
export const PICTURES_ERROR = "PICTURES_ERROR";
export const RESET_GALLERY = "RESET_GALLERY";
export const INCREMENT_INDEXPAGE = "INCREMENT_INDEXPAGE";
